version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Japan
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 5.8.0
    - 6.0.0
    - 6.1.1
    - 6.3.0
    - 6.4.1
    - 6.5.0
    - 6.5.2
    - 6.6.0
    - 6.6.1
    - 6.6.2
    - 6.6.3
    - 7.0.1
    - 8.0.0
    - 8.1.0
  - dependency-name: fonttools
    versions:
    - 4.20.0
    - 4.21.1
    - 4.22.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pydantic
    versions:
    - "1.8"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Japan
  open-pull-requests-limit: 10
